### ISSUE TITLE
ATbar doesn't work and breaks page layout

### ISSUE THREAD

**Issue by CamBanfield** [marxjohnson/moodle-block_accessibility#93] opened 2015-08-14 10:00 UTC
When attempting to launch the ATbar it breaks the layout of the website and doesn't work, the bar fails to display. It looks like it's hiding under the navigation bar. 

I have tested this with the Clean theme on Moodle 2.7.8, I also tested on Moodle 2.7.9 also using the Clean theme.

I can see that the ATbar js is being included from a remote source, I wonder if they have updated it which has started to cause these issues!

If you want any more info just let me know :)

Thanks

**Comment by marxjohnson** [comment] 2016-06-21 09:16
#102 is a duplicate of this, but has more info so I'll close this one.

**Closed by marxjohnson** 2016-06-21 09:16 UTC
